name: Build parser

on:
  workflow_dispatch:
    inputs:
      npmPackageName:
        description: "NPM package name of parser to build"
        type: string
        required: true
      parserName:
        description: ".wasm file name of parser (without .wasm extension), defaults to npmPackageName"
        type: string
        required: true
      subdirectory:
        description: "Subdirectory containing the parser grammar"
        type: string
        required: false
        default: ""

jobs:
  build:
    name: Build parser
    concurrency: ${{ inputs.npmPackageName }}-${{ inputs.parserName }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build tag
        run: |
          echo "PARSER_TAG=${{ inputs.npmPackageName }}-${{ inputs.parserName }}-$(npm view ${{ inputs.npmPackageName }} version)" >> $GITHUB_ENV
      - name: Check if tag exists
        run: |
          git fetch --all --tags
          git tags --list | grep $PARSER_TAG
      - name: Install tree-sitter cli
        run: npm install --global tree-sitter-cli
      - name: Download parser
        run: npm pack --verbose --json --pack-destination . ${{ inputs.npmPackageName }}
      - name: Build parser
        # will use docker to build parser
        run: tree-sitter build-wasm ${{ inputs.subdirectory }}
      - name: Commit parser
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "github-actions"
          git pull --ff-only origin ${{ github.ref_name }}
          git add ${{ inputs.parserName }}.wasm
          git commit -m "Update ${{ inputs.parserName }} [skip ci]"
          git tag $(echo $PARSER_TAG)
          git push --tags
